### ISSUE TITLE
Do you have forked this from https://github.com/lawfx/YoutubeNonStop ?

### ISSUE THREAD

**Issue by DanielOberlechner** [BPower0036/YT-Nonstop#10]
Hi,
I looked first at https://github.com/lawfx/YoutubeNonStop and have this plugin installed.
Then somehow I came to your github site and it looks like you almost have the same plugin as listed above?

Does this have a good reason?
Is the other repo not accepting pull requests or why do such similar projects exist?

I do wonder which one works better and gets more updates.

Kind regards,
Daniel Oberlechner

**Comment by Nomes77** [comment]
Yes, I have fork it from https://github.com/lawfx/YoutubeNonStop.
But that repo is not very active plus in my opinion my extension/addon works better. The code much shorter and so not unneccesary long [See PR](https://github.com/lawfx/YoutubeNonStop/pull/43).
Futhermore, my extension has an extra option to disable autoplay or automaticly click 'next video' button.
Last but not least `@lawfx` is not fast with reacting to issues or pr's.

My extension got more updates, but there currently no updates needed, unless Youtube change their code.

Kind regards,
BPower0036

**Comment by DanielOberlechner** [comment]
Cool thats lovely!
Do you have released your plugin in the chrome store as well?
I would like to download it via the chrome store if possible.

I've read here that you were searching for help in one of the issues?
Is that still a thing?
Did you try to update to the manifest version 3 and you had issues doing that?

Daniel

**Comment by Nomes77** [comment]
My plugin isn't released to the chrome store, because Google ask money for it and I don't have a credit card.

Secondly, i tried updating the plugin to manifest 3. (See for that code https://github.com/BPower0036/YT-Nonstop/tree/manifest_3).
But then the autoskip part gives the error mentioned in issue #8.
The issue is still there because I don't know how to solve it.

Good to know, is that i don't have any tech knowledge. Everything I have done, is because i saw how other people did it.
So I have acctually no tech knowledge.

**Comment by DanielOberlechner** [comment]
Why did you obfuscate the code?! Did you try to optimise it this way?
In my opinion thats not so smart, because the file is only a few kB why change that?

I have a google verified account and I could upload the plugin to the store and give you the credits for it if you want to.
The chrome store is a good place to get more users and in my opinion that would make sense for this plugin.

I'm a beginner/advanced programmer myself and I don't know even a lot of things.
Did i possibly find the solution to the problem?
Take a look at this:
https://stackoverflow.com/questions/16145522/chrome-showing-error-as-refused-to-execute-inline-script-because-of-content-sec

The first answer should be key to this problem!


Daniel

**Comment by Nomes77** [comment]
Yes, i wanted to optimise the code.
Your link is the key to the solution of the problem
However, after 6 times trying, I don't know how to do it.

**Comment by DanielOberlechner** [comment]
In your latest version 1.1.1 you removed all the content of autoconfirm.js !!!
Why did you do that? 

And the obfuscation is also only an obstacle then help, it would be better to have the normal code!

In my opinion you should forget the last 2 commits and start again from version 1.0.4 !

I'll try my best to help you with this.
Maybe you want get in touch via Discord or a similar service?

Daniel

**Comment by Nomes77** [comment]
As you can see in this [PR comment](https://github.com/lawfx/YoutubeNonStop/pull/43#issuecomment-954689654) and [Issue](https://github.com/lawfx/YoutubeNonStop/issues/25)  making `autoconfirm.js` this short is possible and it works. So why making it longer, if shorter is also possibly.
There is no obfuscation in version 1.1.1! Everything there is clear.

**Comment by DanielOberlechner** [comment]
Ok I understand now. I've read all the PR's and Issue comments and now I'm up2date.
In my opinion this method won't work all the time, why?
Because if I remember right youtube doesn't only has the trigger after 15 minutes the popup will come out, there is also after 10-15 videos with for ex. 2-3 seconds length each the popup will show up as well.

I don't think your solution will work all the time.
Maybe it would be smarter to wait until the popup shows up and then autoclick it away.

But this is just my opinion.

Would you be interested to upload this plugin over my account and mention only you in the credits?

Daniel

**Comment by Nomes77** [comment]
>  Maybe it would be smarter to wait until the popup shows up and then autoclick it away.

Maybe you're true, but I never had a problem with it plus if others encounters problems with it, they could report it and then I can change it back.

> Would you be interested to upload this plugin over my account and mention only you in the credits?

Yeah, that would be great.
Thank you for your interest in this project!

**Comment by DanielOberlechner** [comment]
Would it be the best first to update to the new manifest version?
That is quite important in my opinion but you said that your not able to do that?
Have you a Discord Name? Would be easier to exchange messages via Discord ...

**Comment by Nomes77** [comment]
Yes, I am not able to do that
And no, I don't have a Discord server.  **_EDIT:_** also no Discord Name

Good to know, this is what i already have:  https://github.com/BPower0036/YT-Nonstop/tree/manifest_3

**Comment by DanielOberlechner** [comment]
I wasn't asking for a Discord server but for a Discord Name. It works like Skype does work. But ok.
Yeah let me tinker around a little bit and we will see if I can to get it work.
Daniel

**Comment by DanielOberlechner** [comment]
Hi @BPower0036,
I found the issue why the plugin isn't working! :)

Got it now to work.
Are there other things left to do, or was the background.js your only problem?
Is there something to do to get it compatible with the manifest version 3?

I would have now a PR ready,
but I'll wait for your answer first.

Are you fine with it,
if I publish then this plugin in the chrome store,
and link to your repository here on github?

Kind regards,
Daniel :)

**Comment by Nomes77** [comment]
@DanielOberlechner The only compatibility issue with manifest version 3 was the problem with de `script.js` (#8 )

So yeah, I am fine with it if you pubish this plugin in the chrome store.

Tanks for your help!
Kind regards,
BPower0036 :)

**Comment by Nomes77** [comment]
@DanielOberlechner I haven't heard from you in a long time. You said last time that you found the problem. Can you share your solution with me so I can update my extension?

**Comment by DanielOberlechner** [comment]
Hi @BPower0036,
back then when I "fixed" the problem I was approaching a different type of solution.
Here I can show you briefly what I tried:
https://gist.github.com/DanielOberlechner/6f3666a78bfa9552dff4e3f6fb7e40a2

However this works not quite as I would have expected.
Maybe you would feel confident enough to tinker around with this script I wrote?

The other problem which you've explained in Issue 8 still consists ...
I couldn't really find a way around it.

Here is the working manifest json:
https://gist.github.com/DanielOberlechner/6f3666a78bfa9552dff4e3f6fb7e40a2

Do you think you have enough hints to solve the problem now?

If you need help or some information just hit me up here on github!

Kind regards,
Daniel Oberlechner :)

**Comment by JohnyP36** [comment]
@DanielOberlechner How can you add a timestamp to the console log as in your code?

---
Should I add below `// custom quick functions`

```
  function () {
    const tag = '[YT Nonstop]';
    const isYoutubeMusic = window.location.hostname === 'music.youtube.com';

    function log(message) {
      console.log(`${tag}[${getTimestamp()}] ${message}`);
    }

    function asDoubleDigit(value) {
      return value < 10 ? '0' + value : value;
    }

    function getTimestamp() {
      let dt = new Date();
      let time = asDoubleDigit(dt.getHours()) + ':' + asDoubleDigit(dt.getMinutes()) + ':' + asDoubleDigit(dt.getSeconds());
      return time;
    }
```

**Comment by DanielOberlechner** [comment]
Hey @BPower0036,
I usually do timestamp's with the javascript's date class.
I think I find a good example for you:
https://stackoverflow.com/questions/221294/how-do-you-get-a-timestamp-in-javascript

Are there still issues or do you think you can get this code running?

Kind regards,
Daniel Oberlechner

**Comment by Nomes77** [comment]
@DanielOberlechner It does work. However I can't get issue #8 solved.
I have tried a lot. But it doesn't solve it. I think I have too less knowledge of javascript.
I think I will waite until updates [AutoTube - YouTube nonstop](https://chrome.google.com/webstore/detail/autotube-youtube-nonstop/egobelhdffdoidcnhpgkngoghpiebial) his extension to manifest 3, because I borrowed the autoplay part from him
