### ISSUE TITLE
Playlists issue

### ISSUE THREAD

**Issue by gtroeno** [BPower0036/YT-Nonstop#5]
Hey @BPower0036, proud user of the YT-Nonstop extension here.

Seems like YT (or maybe the Edge browser?) changed something lately, which causes the extension to not _always_ work anymore. Although, most of the time it does.

I understand that's a bit vague, so allow me to explain;

Mostly I play music playlists on YT - as a regular user though, I'm _not_ an YT Music or a paying YT user in any way. 
Until about 1 or 2 weeks ago, YT-Nonstop always did its job without any problems: I never had to confirm the "_video is paused_" dialog.

Last week I noticed the music stopped and when I opened the YT window, it had the "_video is paused_" dialog open. 
First thing I checked was if YT-Nonstop was active and running: found out it was (always is :). 
Looked up if maybe I had to update either the extension or browser, so I updated everything as well.

But it still occurs:
- I've noticed it never happens during playing a video, but **when the playlist loads to the next video automatically**.
I.e. everytime a video in the playlist ends, then loads next video, sometimes it opens that video with the "_video is paused_" dialog.
- However, this occurs occassionally as well - sometimes it even seems randomly..
But I've noticed it mostly occurs when letting the playlist run in the background passively for a while.
- Once a video is played, then YT-Nonstop does its job well again, because then the video never pauses and the dialog doesn't appear.

Tried to reproduce the behaviour, but when manually playing a previous or next video from the list, it doesn't occur. 
It always occurs during the (auto) switch to next video in the playlist and after I've left it running for some time.

Considering this behaviour I'm guessing that YT recently built in a some kind check if the user has been inactive for some kind of period; then when it switches to a next vid, plus has registered an x amount of time of passiveness, it has the opportunity to pause the video and loads the dialog..
But that's just guessing ;) 

**Current info:**
- Edge v93.0.961.52 on Win10 Pro x64
- Running YT-Nonstop alongside:
-- [AdBlocker Ultimate](https://microsoftedge.microsoft.com/addons/detail/adblocker-ultimate/pciakllldcajllepkbbihkmfkikheffb)
-- [Auto HD for YT](https://chrome.google.com/webstore/detail/auto-hd4k8k-for-youtube-y/fjdmkanbdloodhegphphhklnjfngoffa) 

Hope this helps because I really like this extension!

**Comment by Nomes77** [comment]
A question. If the video opens with the "video is paused" dialog is the video then paused or does it still played but with the dialog in front?

**Comment by gtroeno** [comment]
Good question, I didn't mention it but it kind of happens both:
- Sometimes I go to the YT browser window and I can see the dialog open while the video is playing anyway.
In this case, I always think it's just a little 'buggy' but it isn't a real issue. You can click it away and have no further problems, video doesn't pause and YT-Nonstop still does its job :)

- When the real issue occurs (auto playing next video in a playlist), then the video is paused / stopped and the dialog is open.

**Comment by Nomes77** [comment]
Because I don't have the time to repoduce en test my solution, I will do it on Monday.
And then I will update the extionsion in the Stores.
I hope you're fine with it.

**Comment by JohnyP36** [comment]
The only thing I know is that this happens because the YouTube tab is at the background and for some reason the extension wouldn't right away click on the dialog until you open the tab. 

**Edit**: I can't see something in the (newest) code that may cause this "bug" sometimes.

**Comment by gtroeno** [comment]
@BPower0036 
Apologies for my late reaction. Yes no worries, I was totally fine with that, I didn't mean to rush you at all. Just noticed this behaviour and thought let me notify the dev ;)

Thank you that you wanted to take time & put in efforts looking into this and if it occurs again I'll notify here.
