### ISSUE TITLE
`show_matches` in manifest file

### ISSUE THREAD

**Issue by JohnyP36** [BPower0036/YT-Nonstop#9]
https://github.com/BPower0036/YT-Nonstop/blob/1ad3f2bceb40fe3614457b93a8ab1f9046807125/manifest.json#L20

As your extension only runs on the domains you have under `permission` this line seems unnecessary to me. 
And could been removed.

###### I don't know if this rule is required for Firefox.

**Comment by Nomes77** [comment]
In Firefox it is needed in combination with `"page_action" {` to show the extensions/add-on button in the urlbar in stead of the navigationbar
